### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by bbawtm** [JohnReeze/TinkoffInvestSwiftSDK#4]
Кажется, название проекта в specs должно быть `TinkoffInvestSwiftSDK`, а там стоит `TinkoffInvestSDK`. Это вызывает ошибку `Unable to find a specification for 'TinkoffInvestSwiftSDK'.`

**Comment by JohnReeze** [comment]
Странно косякнул – поправил документацию. 
Вот так должно работать 
```
pod 'TinkoffInvestSDK', :git => "https://github.com/JohnReeze/TinkoffInvestSwiftSDK.git", :tag => "0.5.0"
```

Спасибо за фидбек!
